name: Convert and upload unit test report

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    env:
      TEST_REPORT_FILE: "test_report.xml"
      VERSION: "1.0.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: python -m pip install pytest

      - name: Test with pytest
        run: python -m pytest --junitxml=$TEST_REPORT_FILE test.py

      - name: Upload test reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_report.xml
          path: ${{ github.workspace }}/$TEST_REPORT_FILE

      - name: Run Docker image for test upload and convert
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: 65edfd3b/test_report_upload:latest
          options: |
            --mount type=bind,source=${{ github.workspace }}/$TEST_REPORT_FILE,target=/app/$TEST_REPORT_FILE
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -e S3_PATH=qa

          run: |
            /bin/bash -c "/app/convert_and_push.sh $VERSION"
