######################################################################################################################
# This workflow runs unit tests stored in the repository
######################################################################################################################
name: run-unit-tests
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - labeled
  push:
    branches:
      - main
      - release/*

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')) == 'true' }}
      matrix:
        services:
          - "test"
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF#refs/heads/release/)" >> $GITHUB_ENV
      - name: Debug boolean conditions
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Is Push Event: ${{ github.event_name == 'push' }}"
          echo "Starts with refs/heads/release/: ${{ startsWith(github.ref, 'refs/heads/release/') }}"
          echo "Combined Condition: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')}}"
          echo "$GITHUB_WORKSPACE/test_reports/${{matrix.services}}-test_report.xml"
      - name: Convert and Push ${{matrix.services}} Test Report to
        uses: bcaglaraydin/s3_test_report_repo_maker@main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        with:
          s3-bucket-base-path: s3://empatica-test-reports-data
          s3-path: qa/test
          test-report-filename: ./test_reports/${{matrix.services}}-test_report.xml
          version: $BRANCH_NAME
        if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/') && (failure() || success())}}
